package com.ai.demo.utils;

import java.util.Collections;
import java.util.SortedMap;
import java.util.TreeMap;
import lombok.AccessLevel;
import lombok.NoArgsConstructor;

@NoArgsConstructor(access = AccessLevel.PRIVATE)
public final class CountryCodesUtil {
    public static final SortedMap<String, String> ISO_COUNTRIES = Collections.unmodifiableSortedMap(buildISOCountryMap());

    private static TreeMap<String, String> buildISOCountryMap() {

        TreeMap<String, String> countries = new TreeMap<>(String.CASE_INSENSITIVE_ORDER);

        countries.put("AD", "Andorra, Principality Of");
        countries.put("AE", "United Arab Emirates");
        countries.put("AF", "Afghanistan, Islamic State Of");
        countries.put("AG", "Antigua And Barbuda");
        countries.put("AI", "Anguilla");
        countries.put("AL", "Albania");
        countries.put("AM", "Armenia");
        countries.put("AN", "Netherlands Antilles");
        countries.put("AO", "Angola");
        countries.put("AQ", "Antarctica");
        countries.put("AR", "Argentina");
        countries.put("AS", "American Samoa");
        countries.put("AT", "Austria");
        countries.put("AU", "Australia");
        countries.put("AW", "Aruba");
        countries.put("AZ", "Azerbaidjan");
        countries.put("BA", "Bosnia-Herzegovina");
        countries.put("BB", "Barbados");
        countries.put("BD", "Bangladesh");
        countries.put("BE", "Belgium");
        countries.put("BF", "Burkina Faso");
        countries.put("BG", "Bulgaria");
        countries.put("BH", "Bahrain");
        countries.put("BI", "Burundi");
        countries.put("BJ", "Benin");
        countries.put("BM", "Bermuda");
        countries.put("BN", "Brunei Darussalam");
        countries.put("BO", "Bolivia");
        countries.put("BR", "Brazil");
        countries.put("BS", "Bahamas");
        countries.put("BT", "Bhutan");
        countries.put("BV", "Bouvet Island");
        countries.put("BW", "Botswana");
        countries.put("BY", "Belarus");
        countries.put("BZ", "Belize");
        countries.put("CA", "Canada");
        countries.put("CC", "Cocos (Keeling) Islands");
        countries.put("CF", "Central African Republic");
        countries.put("CD", "Congo, The Democratic Republic Of The");
        countries.put("CG", "Congo");
        countries.put("CH", "Switzerland");
        countries.put("CI", "Ivory Coast (Cote D'Ivoire)");
        countries.put("CK", "Cook Islands");
        countries.put("CL", "Chile");
        countries.put("CM", "Cameroon");
        countries.put("CN", "China");
        countries.put("CO", "Colombia");
        countries.put("CR", "Costa Rica");
        countries.put("CS", "Former Czechoslovakia");
        countries.put("CU", "Cuba");
        countries.put("CV", "Cape Verde");
        countries.put("CX", "Christmas Island");
        countries.put("CY", "Cyprus");
        countries.put("CZ", "Czech Republic");
        countries.put("DE", "Germany");
        countries.put("DJ", "Djibouti");
        countries.put("DK", "Denmark");
        countries.put("DM", "Dominica");
        countries.put("DO", "Dominican Republic");
        countries.put("DZ", "Algeria");
        countries.put("EC", "Ecuador");
        countries.put("EE", "Estonia");
        countries.put("EG", "Egypt");
        countries.put("EH", "Western Sahara");
        countries.put("ER", "Eritrea");
        countries.put("ES", "Spain");
        countries.put("ET", "Ethiopia");
        countries.put("FI", "Finland");
        countries.put("FJ", "Fiji");
        countries.put("FK", "Falkland Islands");
        countries.put("FM", "Micronesia");
        countries.put("FO", "Faroe Islands");
        countries.put("FR", "France");
        countries.put("FX", "France (European Territory)");
        countries.put("GA", "Gabon");
        countries.put("UK", "United Kingdom");
        countries.put("GD", "Grenada");
        countries.put("GE", "Georgia");
        countries.put("GF", "French Guyana");
        countries.put("GH", "Ghana");
        countries.put("GI", "Gibraltar");
        countries.put("GL", "Greenland");
        countries.put("GM", "Gambia");
        countries.put("GN", "Guinea");
        countries.put("GP", "Guadeloupe (French)");
        countries.put("GQ", "Equatorial Guinea");
        countries.put("GR", "Greece");
        countries.put("GS", "S. Georgia & S. Sandwich Isls.");
        countries.put("GT", "Guatemala");
        countries.put("GU", "Guam (USA)");
        countries.put("GW", "Guinea Bissau");
        countries.put("GY", "Guyana");
        countries.put("HK", "Hong Kong");
        countries.put("HM", "Heard And McDonald Islands");
        countries.put("HN", "Honduras");
        countries.put("HR", "Croatia");
        countries.put("HT", "Haiti");
        countries.put("HU", "Hungary");
        countries.put("ID", "Indonesia");
        countries.put("IE", "Ireland");
        countries.put("IL", "Israel");
        countries.put("IN", "India");
        countries.put("IO", "British Indian Ocean Territory");
        countries.put("IQ", "Iraq");
        countries.put("IR", "Iran");
        countries.put("IS", "Iceland");
        countries.put("IT", "Italy");
        countries.put("JM", "Jamaica");
        countries.put("JO", "Jordan");
        countries.put("JP", "Japan");
        countries.put("KE", "Kenya");
        countries.put("KG", "Kyrgyz Republic (Kyrgyzstan)");
        countries.put("KH", "Cambodia, Kingdom Of");
        countries.put("KI", "Kiribati");
        countries.put("KM", "Comoros");
        countries.put("KN", "Saint Kitts & Nevis Anguilla");
        countries.put("KP", "North Korea");
        countries.put("KR", "South Korea");
        countries.put("KW", "Kuwait");
        countries.put("KY", "Cayman Islands");
        countries.put("KZ", "Kazakhstan");
        countries.put("LA", "Laos");
        countries.put("LB", "Lebanon");
        countries.put("LC", "Saint Lucia");
        countries.put("LI", "Liechtenstein");
        countries.put("LK", "Sri Lanka");
        countries.put("LR", "Liberia");
        countries.put("LS", "Lesotho");
        countries.put("LT", "Lithuania");
        countries.put("LU", "Luxembourg");
        countries.put("LV", "Latvia");
        countries.put("LY", "Libya");
        countries.put("MA", "Morocco");
        countries.put("MC", "Monaco");
        countries.put("MD", "Moldavia");
        countries.put("MG", "Madagascar");
        countries.put("MH", "Marshall Islands");
        countries.put("MK", "Macedonia");
        countries.put("ML", "Mali");
        countries.put("MM", "Myanmar");
        countries.put("MN", "Mongolia");
        countries.put("MO", "Macau");
        countries.put("MP", "Northern Mariana Islands");
        countries.put("MQ", "Martinique (French)");
        countries.put("MR", "Mauritania");
        countries.put("MS", "Montserrat");
        countries.put("MT", "Malta");
        countries.put("MU", "Mauritius");
        countries.put("MV", "Maldives");
        countries.put("MW", "Malawi");
        countries.put("MX", "Mexico");
        countries.put("MY", "Malaysia");
        countries.put("MZ", "Mozambique");
        countries.put("NA", "Namibia");
        countries.put("NC", "New Caledonia (French)");
        countries.put("NE", "Niger");
        countries.put("NF", "Norfolk Island");
        countries.put("NG", "Nigeria");
        countries.put("NI", "Nicaragua");
        countries.put("NL", "Netherlands");
        countries.put("NO", "Norway");
        countries.put("NP", "Nepal");
        countries.put("NR", "Nauru");
        countries.put("NT", "Neutral Zone");
        countries.put("NU", "Niue");
        countries.put("NZ", "New Zealand");
        countries.put("OM", "Oman");
        countries.put("PA", "Panama");
        countries.put("PE", "Peru");
        countries.put("PF", "Polynesia (French)");
        countries.put("PG", "Papua New Guinea");
        countries.put("PH", "Philippines");
        countries.put("PK", "Pakistan");
        countries.put("PL", "Poland");
        countries.put("PM", "Saint Pierre And Miquelon");
        countries.put("PN", "Pitcairn Island");
        countries.put("PR", "Puerto Rico");
        countries.put("PT", "Portugal");
        countries.put("PW", "Palau");
        countries.put("PY", "Paraguay");
        countries.put("QA", "Qatar");
        countries.put("RE", "Reunion (French)");
        countries.put("RO", "Romania");
        countries.put("RU", "Russian Federation");
        countries.put("RW", "Rwanda");
        countries.put("SA", "Saudi Arabia");
        countries.put("SB", "Solomon Islands");
        countries.put("SC", "Seychelles");
        countries.put("SD", "Sudan");
        countries.put("SE", "Sweden");
        countries.put("SG", "Singapore");
        countries.put("SH", "Saint Helena");
        countries.put("SI", "Slovenia");
        countries.put("SJ", "Svalbard And Jan Mayen Islands");
        countries.put("SK", "Slovak Republic");
        countries.put("SL", "Sierra Leone");
        countries.put("SM", "San Marino");
        countries.put("SN", "Senegal");
        countries.put("SO", "Somalia");
        countries.put("SR", "Suriname");
        countries.put("ST", "Saint Tome (Sao Tome) And Principe");
        countries.put("SU", "Former USSR");
        countries.put("SV", "El Salvador");
        countries.put("SY", "Syria");
        countries.put("SZ", "Swaziland");
        countries.put("TC", "Turks And Caicos Islands");
        countries.put("TD", "Chad");
        countries.put("TF", "French Southern Territories");
        countries.put("TG", "Togo");
        countries.put("TH", "Thailand");
        countries.put("TJ", "Tadjikistan");
        countries.put("TK", "Tokelau");
        countries.put("TM", "Turkmenistan");
        countries.put("TN", "Tunisia");
        countries.put("TO", "Tonga");
        countries.put("TP", "East Timor");
        countries.put("TR", "Turkey");
        countries.put("TT", "Trinidad And Tobago");
        countries.put("TV", "Tuvalu");
        countries.put("TW", "Taiwan");
        countries.put("TZ", "Tanzania");
        countries.put("UA", "Ukraine");
        countries.put("UG", "Uganda");
        countries.put("UM", "USA Minor Outlying Islands");
        countries.put("US", "United States");
        countries.put("UY", "Uruguay");
        countries.put("UZ", "Uzbekistan");
        countries.put("VA", "Holy See (Vatican City State)");
        countries.put("VC", "Saint Vincent & Grenadines");
        countries.put("VE", "Venezuela");
        countries.put("VG", "Virgin Islands (British)");
        countries.put("VI", "Virgin Islands (USA)");
        countries.put("VN", "Vietnam");
        countries.put("VU", "Vanuatu");
        countries.put("WF", "Wallis And Futuna Islands");
        countries.put("WS", "Samoa");
        countries.put("YE", "Yemen");
        countries.put("YT", "Mayotte");
        countries.put("YU", "Yugoslavia");
        countries.put("ZA", "South Africa");
        countries.put("ZM", "Zambia");
        countries.put("ZR", "Zaire");
        countries.put("ZW", "Zimbabwe");

        return countries;
    }

}
