-- User Profile
CREATE TABLE user_travel_profiles
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(255) NOT NULL,
    birth            DATE,
    gender           VARCHAR(50),
    budget_level     VARCHAR(50),
    travel_style     VARCHAR(255),
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_preferred_climates
(
    user_profile_id BIGINT NOT NULL,
    climate         VARCHAR(255),
    FOREIGN KEY (user_profile_id) REFERENCES user_travel_profiles (id) ON DELETE CASCADE
);

CREATE TABLE user_languages
(
    user_profile_id BIGINT NOT NULL,
    language        VARCHAR(255),
    FOREIGN KEY (user_profile_id) REFERENCES user_travel_profiles (id) ON DELETE CASCADE
);

CREATE TABLE user_passports
(
    user_profile_id BIGINT NOT NULL,
    country_code    VARCHAR(10),
    FOREIGN KEY (user_profile_id) REFERENCES user_travel_profiles (id) ON DELETE CASCADE
);

-- User Interests
CREATE TABLE user_interests
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  BIGINT NOT NULL,
    interest VARCHAR(255),
    FOREIGN KEY (user_id) REFERENCES user_travel_profiles (id) ON DELETE CASCADE
);

-- Travel Plan
CREATE TABLE travel_plans
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_profile_id  BIGINT NOT NULL,
    start_date       DATE,
    end_date         DATE,
    trip_type        VARCHAR(50),
    notes            VARCHAR(1000),
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_profile_id) REFERENCES user_travel_profiles (id) ON DELETE CASCADE
);

CREATE TABLE travel_plan_traveler_types
(
    travel_plan_id BIGINT NOT NULL,
    traveler_type  VARCHAR(50),
    FOREIGN KEY (travel_plan_id) REFERENCES travel_plans (id) ON DELETE CASCADE
);


-- TravelPlan Destinations (as ElementCollection)
CREATE TABLE travel_plan_destinations
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    travel_plan_id   BIGINT       NOT NULL,
    from_country          VARCHAR(5) NOT NULL,
    from_city          VARCHAR(100) NOT NULL,
    to_country          VARCHAR(5) NOT NULL,
    to_city             VARCHAR(100),
    start_date       DATE,
    end_date         DATE,
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (travel_plan_id) REFERENCES travel_plans (id) ON DELETE CASCADE
);


-- User Recommendations
CREATE TABLE user_recommendations
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_profile_id  BIGINT NOT NULL,
    content          VARCHAR(2000),
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_profile_id) REFERENCES user_travel_profiles (id) ON DELETE CASCADE
);

-- Budget Estimations
CREATE TABLE budget_estimations
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    travel_plan_id   BIGINT NOT NULL,
    total_estimation NUMERIC(15, 2),
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_budget_estimation_travel_plan FOREIGN KEY (travel_plan_id) REFERENCES travel_plans (id) ON DELETE CASCADE
);

-- Budget Breakdowns
CREATE TABLE budget_estimation_breakdowns
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    budget_estimation_id       BIGINT NOT NULL,
    travel_plan_destination_id BIGINT NOT NULL,
    estimation                 NUMERIC(15, 2),
    notes                      VARCHAR(4000),
    created_at                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_breakdown_budget FOREIGN KEY (budget_estimation_id) REFERENCES budget_estimations (id) ON DELETE CASCADE,
    CONSTRAINT fk_breakdown_destination FOREIGN KEY (travel_plan_destination_id) REFERENCES travel_plan_destinations (id) ON DELETE CASCADE
);

CREATE TABLE budget_breakdown_costs
(
    id                             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    budget_estimation_breakdown_id BIGINT NOT NULL,
    estimation                     NUMERIC(15, 2),
    notes                          VARCHAR(1000),
    description                    VARCHAR(200),
    created_at                     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_at               TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_breakdown_costs_budget_breakdowns FOREIGN KEY (budget_estimation_breakdown_id) REFERENCES budget_estimation_breakdowns (id) ON DELETE CASCADE
);