-- User Profile
CREATE TABLE user_travel_profiles
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(255) NOT NULL,
    birth            DATE,
    gender           VARCHAR(50),
    budget_level     VARCHAR(50),
    travel_style     VARCHAR(255),
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_preferred_climates
(
    user_profile_id BIGINT NOT NULL,
    climate         VARCHAR(255),
    FOREIGN KEY (user_profile_id) REFERENCES user_travel_profiles (id) ON DELETE CASCADE
);

CREATE TABLE user_languages
(
    user_profile_id BIGINT NOT NULL,
    language        VARCHAR(255),
    FOREIGN KEY (user_profile_id) REFERENCES user_travel_profiles (id) ON DELETE CASCADE
);

CREATE TABLE user_passports
(
    user_profile_id BIGINT NOT NULL,
    country_code    VARCHAR(10),
    FOREIGN KEY (user_profile_id) REFERENCES user_travel_profiles (id) ON DELETE CASCADE
);

-- User Interests
CREATE TABLE user_interests
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  BIGINT NOT NULL,
    interest VARCHAR(255),
    FOREIGN KEY (user_id) REFERENCES user_travel_profiles (id) ON DELETE CASCADE
);

-- Travel Plan
CREATE TABLE travel_plans
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_profile_id       BIGINT NOT NULL,
    destination_countries TEXT[], -- PostgreSQL array type
    destination_cities    TEXT[], -- PostgreSQL array type
    start_date            DATE,
    end_date              DATE,
    trip_type             VARCHAR(50),
    notes                 VARCHAR(1000),
    FOREIGN KEY (user_profile_id) REFERENCES user_travel_profiles (id) ON DELETE CASCADE
);

-- User Recommendations
CREATE TABLE user_recommendations
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_profile_id  BIGINT NOT NULL,
    content          VARCHAR(2000),
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_profile_id) REFERENCES user_travel_profiles (id) ON DELETE CASCADE
);
