-- Users
CREATE TABLE app_user (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          username VARCHAR(15) NOT NULL UNIQUE,
                          country VARCHAR(50),
                          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                          updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_country ON app_user (country);

-- Accounts
CREATE TABLE account (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         description VARCHAR(100),
                         amount_gross NUMERIC(19, 2),
                         amount_net NUMERIC(19, 2),
                         type VARCHAR(50) NOT NULL,
                         date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         user_id BIGINT NOT NULL,
                         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                         updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Account History
CREATE TABLE account_history (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 amount NUMERIC(19, 2),
                                 date TIMESTAMP,
                                 account_id BIGINT NOT NULL,
                                 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Retirement Detail
CREATE TABLE retirement_detail (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   income_per_month_desired NUMERIC(19, 2),
                                   life_expcetation DATE,
                                   retirement_date DATE,
                                   user_id BIGINT NOT NULL UNIQUE,
                                   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
